export const popularConstants = {
    FETCH_POPULAR_BEGIN: 'FETCH_POPULAR_BEGIN',
    FETCH_POPULAR_SUCCESS: 'FETCH_POPULAR_SUCCESS',
    FETCH_POPULAR_ERROR: 'FETCH_POPULAR_ERROR',
};

export const ratedConstants = {
    FETCH_RATED_BEGIN: 'FETCH_RATED_BEGIN',
    FETCH_RATED_SUCCESS: 'FETCH_RATED_SUCCESS',
    FETCH_RATED_ERROR: 'FETCH_RATED_ERROR',
};

export const onAirConstants = {
    FETCH_ON_AIR_BEGIN: 'FETCH_ON_AIR_BEGIN',
    FETCH_ON_AIR_SUCCESS: 'FETCH_ON_AIR_SUCCESS',
    FETCH_ON_AIR_ERROR: 'FETCH_ON_AIR_ERROR',
};

export const detailConstants = {
    FETCH_DETAIL_BEGIN: 'FETCH_DETAIL_BEGIN',
    FETCH_DETAIL_SUCCESS: 'FETCH_DETAIL_SUCCESS',
    FETCH_DETAIL_ERROR: 'FETCH_DETAIL_ERROR',
};
