export const tvConstants = {
    FETCH_TV_BEGIN: 'FETCH_TV_BEGIN',
    FETCH_TV_SUCCESS: 'FETCH_TV_SUCCESS',
    FETCH_TV_ERROR: 'FETCH_TV_ERROR',
};

export const ratedConstants = {
    FETCH_RATED_BEGIN: 'FETCH_RATED_BEGIN',
    FETCH_RATED_SUCCESS: 'FETCH_RATED_SUCCESS',
    FETCH_RATED_ERROR: 'FETCH_RATED_ERROR',
};

export const onAirConstants = {
    FETCH_ON_AIR_BEGIN: 'FETCH_ON_AIR_BEGIN',
    FETCH_ON_AIR_SUCCESS: 'FETCH_ON_AIR_SUCCESS',
    FETCH_ON_AIR_ERROR: 'FETCH_ON_AIR_ERROR',
};
